# Use uma imagem base do Node.js (ex: LTS v20)
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /app

# A porta do Vite (5173) será exposta no docker-compose.yml
# O 'command' do docker-compose.yml cuidará de instalar
# as dependências (npm install) e iniciar o servidor (npm run dev)