services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-api
    ports:
      - "8000:8000"
    volumes:
      # Montamos o código da aplicação, mas excluímos o vendor para usar o que foi instalado na imagem
      - ./backend:/var/www/html
      - /var/www/html/vendor
    # O entrypoint garante que a preparação do ambiente (migrações, etc.) aconteça antes de iniciar o servidor
    entrypoint: /usr/local/bin/entrypoint.sh
    # O comando principal agora é apenas iniciar o servidor
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - onsky-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "5173:5173"
    volumes:
      # Montamos o código, mas excluímos node_modules para usar o que foi instalado na imagem
      - ./frontend:/app
      - /app/node_modules
    # O comando é simplificado para iniciar o servidor de desenvolvimento
    command: npm run dev -- --host
    networks:
      - onsky-network

networks:
  onsky-network:
    driver: bridge
