/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BotaoPadrao: typeof import('./components/miscellaneous/Botoes/BotaoPadrao.vue')['default']
    BotaoTableAction: typeof import('./components/miscellaneous/Botoes/BotaoTableAction.vue')['default']
    Cabecalho: typeof import('./components/Cabecalho.vue')['default']
    CardNotificacao: typeof import('./components/miscellaneous/Notificacoes/CardNotificacao.vue')['default']
    Contadores: typeof import('./components/Contadores.vue')['default']
    ModalAprovarPedido: typeof import('./components/Modais/ModalAprovarPedido.vue')['default']
    ModalCancelarPedido: typeof import('./components/Modais/ModalCancelarPedido.vue')['default']
    ModalCriarPedido: typeof import('./components/Modais/ModalCriarPedido.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaPedidos: typeof import('./components/TabelaPedidos.vue')['default']
  }
}
